### ISSUE TITLE
Do I have to live in India or be Indian to join?

### ISSUE THREAD

**Issue by JavaCode7** [IndianOpenSourceFoundation/getting-started#4]
I love open source, so this github organization is kind of a dream come true. However, I was wondering if I had to be Indian or live in India to join (I am neither).

**Comment by SulthanNK** [comment]
Hi @JavaCode7 

Glad to hear your interest. There is nothing to be an Indian or need to be live in India to join the organization. The reason for the name "Indian Open Source Foundation" is to mention initialized from India.
